[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "recursive-field-math"
version = "0.1.1"
description = "Projex X1 — Recursive field math (Lucas 4–7–11) with CLI, docs, tests."
readme = "README.md"
license = {text = "MIT License"}
authors = [{name="Commander X (Wizard)"}]
requires-python = ">=3.9"
dependencies = [
    "python-chess>=1.9",
    "numpy>=1.26", 
    "matplotlib>=3.8"
]

[project.scripts]
rfm = "recursive_field_math.cli:main"

[tool.pytest.ini_options]
addopts = "-q"
pythonpath = ["src"]
