[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "recursive-field-math"
version = "0.1.0"
description = "Projex X1 — Recursive field math (Lucas 4–7–11) with CLI, docs, tests."
readme = "README.md"
license = {text = "MIT License"}
authors = [{name="Commander X (Wizard)"}]
requires-python = ">=3.9"
dependencies = []

[project.scripts]
rfm = "recursive_field_math.cli:main"

[tool.pytest.ini_options]
addopts = "-q"
pythonpath = ["src"]

[tool.ruff]
target-version = "py39"

[tool.ruff.lint]
# Additional rules to catch potential issues with attribute vs dictionary access
extend-select = ["B", "SIM"]
select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings  
    "F",  # pyflakes
    "B",  # flake8-bugbear
    "SIM", # flake8-simplify
]
