[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "recursive-field-math"
version = "0.1.0"
description = "Recursive Field Math Pro - Exploring Lucas sequences, Fibonacci, and golden ratio patterns in code for students, researchers, and developers."
readme = "README.md"
license = {text = "MIT License"}
authors = [{name="Commander X (Wizard)"}]
requires-python = ">=3.9"
dependencies = [
    "python-chess>=1.9",
    "numpy>=1.26", 
    "matplotlib>=3.8"
]

[project.scripts]
rfm = "recursive_field_math.cli:main"

[tool.pytest.ini_options]
addopts = "-q"
pythonpath = ["src"]
