[pytest]
testpaths = tests
norecursedirs = clone .git __pycache__ .mypy_cache .tox
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts =
    -v
    --strict-markers
pythonpath = src .
